export interface PortfolioItem {
  id: number;
  slug: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  categoryColor: string;
  year: string;
  image?: string | string[];
  tags: string[];
  link?: string;
  technologies: string[];
  company?: string;
  responsibilities?: string[];
}

export const portfolioData: PortfolioItem[] = [
  {
    id: 0,
    slug: "the-plug-app",
    company: "B ONE CONSULTING",
    title: "The Plug App - Multi-Region Deals & Delivery Platform",
    description:
      "Cross-platform mobile application offering deals and discounts in Bali, food/goods delivery in Miami and Broward (US), and gym membership management in Brazil. Integrated payment gateway and real-time order tracking.",
    category: "marketplace",
    categoryLabel: "Marketplace",
    categoryColor: "orange",
    year: "2025",
    image: "/project/theplugapp.png",
    tags: ["E-commerce", "Delivery", "Mobile App", "Multi-Region"],
    link: "https://theplugapp.com",
    technologies: ["Flutter", "Next.js", "Express.js", "Xendit"],
    responsibilities: [
      "Developed cross-platform mobile app using Flutter for iOS and Android",
      "Implemented multi-region marketplace with region-specific features (Bali, Miami, Brazil)",
      "Integrated Xendit payment gateway for secure transactions",
      "Built real-time order tracking and delivery management system",
      "Designed and implemented gym membership management module",
      "Created responsive admin dashboard using Next.js",
    ],
  },
  {
    id: 1,
    slug: "natalielejeune-lms",
    company: "B ONE CONSULTING",
    title: "Natalielejeune Osteopathy - Learning Management System",
    description:
      "Comprehensive LMS platform with course management, student tracking, assignments, and interactive learning tools for educational institutions.",
    category: "education",
    categoryLabel: "Education",
    categoryColor: "pink",
    year: "2025",
    image: "/project/natalie.png",
    tags: ["LMS", "Education", "E-Learning"],
    technologies: ["ReactJS", "Node.js", "PostgreSQL", "PayPal"],
    link: "https://www.natalielejeuneosteopathy.com/",
    responsibilities: [
      "Architected and developed full-stack LMS platform using ReactJS and Node.js",
      "Implemented course management system with multimedia content support",
      "Built student progress tracking and analytics dashboard",
      "Integrated PayPal payment gateway for course enrollment",
      "Developed assignment submission and grading system",
      "Created interactive learning modules with video and quiz functionality",
    ],
  },

  {
    id: 2,
    slug: "bone-crm",
    company: "B ONE CONSULTING",
    title: "B ONE - Customer Relationship Management",
    description:
      "Advanced CRM system with lead management, sales pipeline, customer analytics, and automated marketing campaigns for growing businesses.",
    category: "enterprise",
    categoryLabel: "Enterprise",
    categoryColor: "green",
    year: "2024",
    image: [
      "/project/bonecrm.png",
      "/project/bonecrm2.png",
      "/project/bonecrm3.png",
      "/project/bonecrm4.png",
      "/project/bonecrm5.png",
      "/project/bonecrm6.png",
    ],
    tags: ["CRM", "Sales", "Enterprise"],
    technologies: [
      "Vue.js",
      "ExpressJS",
      "PostgreSQL",
      "DocuSign",
      "Microsoft Calendar",
    ],
    responsibilities: [
      "Led front-end development using Vue.js with component-based architecture",
      "Built lead management and sales pipeline tracking system",
      "Integrated DocuSign API for automated contract signing workflows",
      "Implemented Microsoft Calendar integration for meeting scheduling",
      "Developed customer analytics dashboard with real-time reporting",
      "Created automated marketing campaign management tools",
    ],
  },
  {
    id: 3,
    slug: "life-id-insurance",
    company: "Barrans Global Mandiri",
    title: "Life Id - Insurance Management System",
    description:
      "Complete insurance platform with policy management, claims processing, customer portal, and automated underwriting for insurance companies.",
    category: "insurance",
    categoryLabel: "Insurance",
    categoryColor: "purple",
    year: "2023",
    image: "/project/lifeid.png",
    tags: ["Insurance", "FinTech", "Claims"],
    link: "https://www.life.id",
    technologies: ["React Native", "NextJS", "Tailwind CSS", "Redux Saga"],
    responsibilities: [
      "Developed mobile app using React Native for insurance policy management",
      "Built customer portal with NextJS and Tailwind CSS",
      "Implemented claims processing workflow with automated status tracking",
      "Integrated Redux Saga for complex state management",
      "Created automated underwriting system with business rule engine",
      "Developed secure document upload and verification features",
    ],
  },
  {
    id: 4,
    slug: "dimedika-medical-record",
    company: "Freelance",
    title: "Dimedika - Medical Record System",
    description:
      "Secure electronic health records system with patient management, appointment scheduling, and medical history tracking for healthcare providers.",
    category: "healthcare",
    categoryLabel: "Healthcare",
    categoryColor: "red",
    year: "2024",
    image: "/project/dimedika.png",
    tags: ["Healthcare", "EHR", "Medical"],
    link: "https://dimedika.id",
    technologies: ["Next.js", "Node.js", "MongoDB", "SHADCN UI"],
    responsibilities: [
      "Architected secure electronic health records system using Next.js",
      "Implemented HIPAA-compliant patient data management",
      "Built appointment scheduling system with calendar integration",
      "Developed medical history tracking with version control",
      "Created responsive UI using SHADCN UI components",
      "Integrated MongoDB for flexible medical data storage",
    ],
  },

  {
    id: 5,
    slug: "bone-hris",
    company: "B ONE CONSULTING",
    title: "B ONE - Human Resource Information System",
    description:
      "Comprehensive HRIS with employee management, payroll processing, performance tracking, and recruitment workflows for modern organizations.",
    category: "hr",
    categoryLabel: "HR",
    categoryColor: "indigo",
    year: "2025",
    image: [
      "/project/bonehris.png",
      "/project/bonehris2.png",
      "/project/bonehris4.png",
      "/project/bonehris5.png",
      "/project/bonehris6.png",
      "/project/bonehris7.png",
      "/project/bonehris9.png",
    ],
    tags: ["HRIS", "HR", "Payroll"],
    technologies: [
      "Vue.js",
      "ExpressJS",
      "PostgreSQL",
      "CronJob",
      "PlopJS",
      "AWS",
    ],
    responsibilities: [
      "Developed comprehensive HRIS platform using Vue.js and ExpressJS",
      "Built automated payroll processing system with tax calculations",
      "Implemented employee performance tracking and review workflows",
      "Created recruitment module with applicant tracking system",
      "Developed automated CronJob for scheduled tasks (payroll, reports)",
      "Deployed and maintained application on AWS infrastructure",
    ],
  },
  {
    id: 6,
    slug: "obs-investment",
    company: "Freelance",
    title: "OBS - Investment Management Platform",
    description:
      "Advanced investment platform with portfolio management, real-time market data, risk analysis, and automated trading strategies for investors.",
    category: "fintech",
    categoryLabel: "FinTech",
    categoryColor: "green",
    year: "2023",
    image:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop&crop=center",
    tags: ["Investment", "Trading", "Finance"],
    technologies: ["ReactJS", "PlopJS", "Material UI", "Micro frontend"],
    responsibilities: [
      "Built investment management platform using micro frontend architecture",
      "Developed portfolio management dashboard with real-time data visualization",
      "Implemented risk analysis tools and investment performance tracking",
      "Created modular UI components using Material UI",
      "Integrated real-time market data feeds for live portfolio updates",
      "Used PlopJS for code generation and consistent project structure",
    ],
  },
  {
    id: 7,
    slug: "sandbox-pos",
    company: "Walden Global Service",
    title: "Sandbox Point of Sale",
    image: "/project/sandboxpos.jpeg",
    description:
      "Modern POS system with inventory management, sales analytics, customer loyalty programs, and multi-payment gateway integration for retail businesses.",
    category: "retail",
    categoryLabel: "Retail",
    categoryColor: "red",
    year: "2022",
    tags: ["POS", "Retail", "Inventory"],
    technologies: ["ReactJS", "Electron", "NodeJS"],
    responsibilities: [
      "Developed cross-platform desktop POS application using Electron",
      "Built inventory management system with real-time stock tracking",
      "Implemented sales analytics and reporting dashboard",
      "Created customer loyalty program with points and rewards system",
      "Integrated multiple payment gateway options for flexible transactions",
      "Designed offline-first architecture for uninterrupted operations",
    ],
  },
  {
    id: 8,
    slug: "msteams-azim",
    company: "Personal Project",
    title: "msteams-azim — Microsoft Teams API Wrapper (NPM)",
    description:
      "Open-source Node.js package for seamless integration with Microsoft Teams APIs, enabling bots, messaging, and automation for business workflows.",
    category: "opensource",
    categoryLabel: "Open Source",
    categoryColor: "pink",
    image: "/project/npm.png",
    year: "2025",
    tags: ["NPM", "Microsoft Teams", "API", "Open Source"],
    link: "https://www.npmjs.com/package/msteams-azim",
    technologies: ["Node.js", "TypeScript", "Microsoft Teams API"],
    responsibilities: [
      "Developed and published open-source NPM package for Microsoft Teams integration",
      "Created TypeScript wrapper for Microsoft Teams APIs with type safety",
      "Implemented bot messaging and automation features",
      "Wrote comprehensive documentation and usage examples",
      "Designed developer-friendly API interface for easy integration",
      "Maintained package with regular updates and bug fixes",
    ],
  },
  {
    id: 9,
    slug: "docusign-azim",
    company: "Personal Project",
    title: "docusign-azim — DocuSign API Wrapper (NPM)",
    description:
      "Node.js package for DocuSign API integration, simplifying e-signature workflows and document automation for web and enterprise apps.",
    category: "opensource",
    categoryLabel: "Open Source",
    categoryColor: "black",
    year: "2025",
    image: "/project/npm.png",
    tags: ["NPM", "DocuSign", "API", "Open Source"],
    link: "https://www.npmjs.com/package/docusign-azim",
    technologies: ["Node.js", "TypeScript", "DocuSign API"],
    responsibilities: [
      "Created open-source NPM package for DocuSign API integration",
      "Built TypeScript wrapper with comprehensive type definitions",
      "Implemented e-signature workflows and document automation features",
      "Simplified complex DocuSign API into developer-friendly methods",
      "Published detailed documentation with code examples",
      "Provided ongoing support and updates for community users",
    ],
  },
  {
    id: 10,
    slug: "tweakmove-pos",
    company: "Walden Global Service",
    title: "TweakMove Desktop - Point of Sale System",
    image: "/project/tweakmove.jpeg",
    description:
      "Desktop POS application built with Electron for cross-platform compatibility. Features real-time inventory tracking, sales reporting, customer management, and offline-first architecture for uninterrupted retail operations.",
    category: "retail",
    categoryLabel: "Retail",
    categoryColor: "red",
    year: "2022",
    tags: ["POS", "Desktop App", "Inventory", "Offline-First"],
    technologies: ["ReactJS", "Electron", "NodeJS"],
    responsibilities: [
      "Developed desktop POS application using ReactJS and Electron",
      "Implemented offline-first architecture with local data synchronization",
      "Built real-time inventory tracking with automatic stock alerts",
      "Created comprehensive sales reporting and analytics features",
      "Developed customer management system with purchase history",
      "Ensured cross-platform compatibility (Windows, macOS, Linux)",
    ],
  },
  {
    id: 11,
    slug: "fishlog-wms",
    company: "Walden Global Service",
    title: "Fishlog WMS - Warehouse Management System",
    image: "/project/fishlogwms.jpeg",
    description:
      "Comprehensive warehouse management system for seafood distribution. Handles inventory tracking, order fulfillment, cold storage monitoring, shipment logistics, and real-time stock level alerts for efficient warehouse operations.",
    category: "logistics",
    categoryLabel: "Logistics",
    categoryColor: "black",
    year: "2022",
    tags: ["WMS", "Warehouse", "Logistics", "Inventory"],
    technologies: ["ReactJS", "Bootstrap", "NodeJS", "PostgreSQL"],
    responsibilities: [
      "Developed warehouse management system for seafood distribution",
      "Implemented inventory tracking with cold storage temperature monitoring",
      "Built order fulfillment workflow with barcode scanning integration",
      "Created shipment logistics management with real-time tracking",
      "Designed stock level alert system for inventory optimization",
      "Developed reporting dashboard for warehouse performance metrics",
    ],
  },
  {
    id: 12,
    slug: "myspace-web",
    company: "PT Sopwer Teknologi Indonesia",
    title: "Keep My Space - Property & Tenant Management",
    image: "/project/myspace.jpeg",
    description:
      "Comprehensive property management platform for managing rental properties, tenant information, lease agreements, payment tracking, and maintenance requests. Streamlines communication between property owners and tenants.",
    category: "proptech",
    categoryLabel: "PropTech",
    categoryColor: "cyan",
    year: "2021",
    tags: ["Property Management", "Tenant", "Real Estate", "Web App"],
    technologies: ["ReactJS", "Node.js", "MongoDB", "Nest.js"],
    responsibilities: [
      "Developed property management platform using ReactJS and Nest.js",
      "Built tenant management system with lease agreement tracking",
      "Implemented payment tracking and automated rent reminders",
      "Created maintenance request workflow with status tracking",
      "Designed communication portal for property owners and tenants",
      "Integrated MongoDB for flexible property data management",
    ],
  },
  {
    id: 13,
    slug: "sherpa",
    company: "PT Sopwer Teknologi Indonesia",
    title: "Sherpa - Product Demand Forecasting System",
    image: "/project/sherpa.jpeg",
    description:
      "Advanced forecasting system using machine learning to predict product demand, optimize inventory levels, and improve supply chain efficiency. Analyzes historical data, market trends, and seasonal patterns for accurate predictions.",
    category: "analytics",
    categoryLabel: "Analytics",
    categoryColor: "purple",
    year: "2022",
    tags: ["Forecasting", "Machine Learning", "Analytics", "Supply Chain"],
    technologies: ["ReactJS", "Python", "TensorFlow", "Node.js", "PostgreSQL"],
    responsibilities: [
      "Developed demand forecasting system using machine learning models",
      "Implemented predictive analytics using Python and TensorFlow",
      "Built data visualization dashboard with ReactJS for forecast insights",
      "Created historical data analysis tools for pattern recognition",
      "Integrated supply chain optimization algorithms",
      "Designed system to analyze seasonal trends and market dynamics",
    ],
  },
  {
    id: 14,
    slug: "sakeena",
    company: "PT Sopwer Teknologi Indonesia",
    title: "Shakeena - Online Kids Book Store",
    image: "/project/sakeena.png",
    description:
      "E-commerce platform specializing in children's books and educational materials. Features age-appropriate book recommendations, curated collections, secure payment gateway, and user-friendly interface for parents to discover quality reading materials for kids.",
    link: "https://shop.sakeenafamily.com/",
    category: "ecommerce",
    categoryLabel: "E-commerce",
    categoryColor: "orange",
    year: "2023",
    tags: ["E-commerce", "Kids", "Books", "Education"],
    technologies: ["ReactJS", "Node.js", "React Native", "Frappe"],
    responsibilities: [
      "Developed e-commerce platform for children's books using ReactJS",
      "Built mobile app with React Native for iOS and Android",
      "Implemented age-based book recommendation engine",
      "Created curated collections and educational content categorization",
      "Integrated secure payment gateway for safe transactions",
      "Designed parent-friendly interface for easy book discovery",
    ],
  },
  {
    id: 15,
    slug: "eroses",
    company: "Freelance",
    title: "EROSES - Electronic Registration of Societies System",
    image: "/project/eroses.png",
    description:
      "Government electronic system for registration and management of associations in Malaysia. Developed for the Registrar of Societies Malaysia (JPPM), providing digital services for society registration, document management, and administrative workflows.",
    link: "https://www.eroses.gov.my/login/",
    category: "government",
    categoryLabel: "Government",
    categoryColor: "teal",
    year: "2024",
    tags: ["Government", "Registration", "Admin Portal", "Malaysia"],
    technologies: ["RefineJS", "ReactJS", "Material UI"],
    responsibilities: [
      "Developed government portal using RefineJS framework",
      "Built society registration system with document upload functionality",
      "Implemented administrative workflows for JPPM officers",
      "Created secure user authentication and role-based access control",
      "Designed Material UI-based interface for government standards",
      "Developed document management system with version control",
    ],
  },
  {
    id: 16,
    slug: "hygearfit",
    company: "Freelance",
    title: "Hygearfit - AI-Powered Fitness Recommendation Engine",
    image: "/project/hygearfit.png",
    description:
      "Smart fitness platform with AI-powered recommendation engine that analyzes real-time performance data to deliver personalized workout routines. Tracks 10+ fitness parameters including calories, weight, power, and speed for data-driven training optimization.",
    link: "https://hygearfit.com/",
    category: "fitness",
    categoryLabel: "Fitness",
    categoryColor: "green",
    year: "2023",
    tags: ["Fitness", "AI", "Health", "Mobile App"],
    technologies: ["ExpressJS", "Mongoose", "MongoDB", "Big Query", "Redis"],
    responsibilities: [
      "Developed AI-powered fitness recommendation engine using machine learning",
      "Built backend API with ExpressJS and MongoDB for data processing",
      "Implemented real-time performance tracking for 10+ fitness metrics",
      "Integrated Big Query for advanced analytics and data insights",
      "Used Redis for caching and real-time data synchronization",
      "Created personalized workout generation algorithms",
    ],
  },
  {
    id: 17,
    slug: "waterhub",
    company: "Freelance",
    title: "Waterhub - IoT Vending Machine App",
    image: "/project/waterhub.png",
    description:
      "IoT-enabled mobile application for smart mineral water vending machines. Provides real-time machine monitoring, cashless payment integration, inventory tracking, and customer management for automated water dispensing systems.",
    link: "https://waterhub.co.id/",
    category: "iot",
    categoryLabel: "IoT",
    categoryColor: "blue",
    year: "2024",
    tags: ["IoT", "Mobile App", "Vending Machine", "Smart Device"],
    technologies: ["Flutter", "Golang", "DIO", "AWS", "PostgreSQL"],
    responsibilities: [
      "Developed IoT-enabled mobile app using Flutter for vending machines",
      "Built backend services with Golang for real-time machine monitoring",
      "Implemented cashless payment integration for seamless transactions",
      "Created inventory tracking system with low-stock alerts",
      "Integrated AWS IoT Core for device communication and management",
      "Developed customer management features with purchase history",
    ],
  },
  {
    id: 18,
    slug: "learnova",
    company: "Freelance",
    title: "Learnova",
    description:
      "Professional certification and training management platform for Indonesia's leading certification body, featuring course registration, competency assessment, and certification tracking for professionals.",
    category: "education",
    categoryLabel: "Education",
    categoryColor: "",
    year: "2026",
    image: "/project/learnova_dashboard.png",
    tags: ["Education", "Certification", "LMS"],
    link: "https://learnovaconsultant.id",
    technologies: [
      "Next.js",
      "Node.js",
      "Go",
      "SHADCN UI",
      "PostgreSQL",
      "GORM",
      "Gin",
    ],
    responsibilities: [
      "Built professional certification management system using Next.js",
      "Developed course and training registration flow for participants",
      "Implemented competency assessment and scoring modules",
      "Created certification tracking and digital certificate generation",
      "Designed responsive UI using SHADCN UI components",
      "Integrated MongoDB for flexible training and user data storage",
    ],
  },
];

export const portfolioCategories = [
  { id: "all", name: "All Projects", color: "gray" },
  { id: "web", name: "Web Development", color: "blue" },
  { id: "mobile", name: "Mobile Apps", color: "green" },
  { id: "ecommerce", name: "E-commerce", color: "purple" },
  { id: "enterprise", name: "Enterprise", color: "indigo" },
];

export const portfolioStats = {
  projectsDelivered: 150,
  clientSatisfaction: 95,
  industriesServed: 25,
  yearsExperience: 5,
};

export const techStack = [
  { name: "React", icon: "⚛️" },
  { name: "Vue.js", icon: "💚" },
  { name: "Angular", icon: "🅰️" },
  { name: "Node.js", icon: "📗" },
  { name: "Laravel", icon: "🔴" },
  { name: "Django", icon: "🐍" },
];
